### ISSUE TITLE
Auto pagination support

### ISSUE THREAD

**Issue by adlerfaulkner** [comake/standard-sdk-js#10]
#### Feature description

Add support for automatic pagination for API operations which support some standard `page` parameter format

**Comment by tarun291** [comment]
Error is occuring while running sdk
node_modules/fontoxpath/dist/fontoxpath.js:76 

value:f.value})));19!==d&&1!==d||e.push(f=>tc(f,b)?{u:!0,value:f}:{u:!1,error:kc(f,b,"pattern validation failed.")});e.push(f=>yc(f,b)?{u:!0,value:f}:{u:!1,error:kc(f,b,"pattern validation failed.")});e.push(f=>({u:!0,value:{type:b,value:f}}));return f=>{f={u:!0,value:f};for(let h=0,k=e.length;h<k&&(f=e[h](f.value),!1!==f.u);++h);return f}}function id(a,b){const c=a.type+1E4*b;let d=gd[c];d||=gd[c]=hd(a.type,b);return d.call(void 0,a.value,b)};function jd(a,b){a=id(a,b);if(!0===a.u)return a.value;throw a.error;};function kd(a){let b=!1;return{next:()=>{if(b)return p;b=!0;return q(a)}}};function ld(a,b){return a===b?!0:a&&b&&a.offset===b.offset&&a.parent===b.parent?ld(a.F,b.F):!1}function md(a,b){return a===b||a.node===b.node&&ld(a.F,b.F)?!0:!1};function nd(a,b,c){var d=x(a,b,null);a=hb(a,d,null);for(let e=0,f=a.length;e<f;++e){d=a[e];if(md(d,b))return-1;if(md(d,c))return 1}}function od(a,b){const c=[];for(;b;b=x(a,b,null))c.unshift(b);return c}function pd(a,b){const c=[];for(;b;b=a.getParentNode(b,null))c.unshift(b);return c}
                                                                                                                                                                                                                                                                                                                                                                                                         ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

**Comment by adlerfaulkner** [comment]
@tarun291 if you are still experiencing this bug, can you please create a new issue for it? It does not seem related to auto pagination. Also, can you provide any additional details about the parameters you are using when this bug happens?
